name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          IMAGE=hello-app
          TAG=${{ github.run_number }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE:$TAG

      - name: Update manifests repo
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: github.com
          username: git
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git clone git@github.com:<teu-usuario>/hello-manifests.git
            cd hello-manifests
            sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.run_number }}|" deployment.yaml
            git add .
            git commit -m "Update image tag"
            git push
